### ISSUE TITLE
Reference to the AOS Method

### ISSUE THREAD

**Issue by RoyiAvital** [Henvezz95/Perona-Malik-Diffusion#1]
Hi,

Is there a reference which shows how you built the AOS matrix?
I can see you work on each row then each columns.

Also, have you seen implementation for the anisotropic case?

**Comment by Henvezz95** [comment]
Hi RoyiAvital,
you can find more information about the implementation [here](https://www.dm.unibo.it/~morigi/homepage_file/courses_file/file_dl/nonlineari_s.pdf).
The slides also contain more information on how the AOS matrix is constructed.

The explicit method solves the anisotropic diffusion equation directly. The semi-implicit method uses a simplification of the equation: the diffusion strength depends on the magnitude of the gradient at that point, but all directions are treated equally. In this way, we can find the solution for each step by solving a tri-diagonal matrix, which is much faster to solve thanks to Thomas's algorithm.
Thus, the process is isotropic at each point, but the strength of the diffusion is different throughout the image. The final diffusion process will still be anisotropic, edges will be preserved and background areas will be smoothed out. You can compare explicit and semi-implicit methods to see that the result is more or less the same.

For more details check [this paper](https://www.researchgate.net/publication/221128740_Parallel_Implementations_of_AOS_Schemes_A_Fast_Way_of_Nonlinear_Diffusion_Filtering) and [this presentation](https://www.mia.uni-saarland.de/Teaching/NAIA07/naia07_e1_slides.pdf).

**Comment by RoyiAvital** [comment]
Hi @Henvezz95, 
Appreciate the response.

The Perona Malik is not considered Anisotropic as it doesn't use the Structure Tensor.
When I asked about the _Anisotropic_ case I meant for methods which does use the _Structure Tensor_.

The resources you linked are great!
Thank you for sharing them.

**Comment by Henvezz95** [comment]
Hi @RoyiAvital,
thanks for the feedback.

Currently, there is no plan to add a method that uses the Structure Tensor since this is quite an old project.
I am happy that you appreciated the additional resources.

**Comment by RoyiAvital** [comment]
Hi @Henvezz95 , 

I meant if you know a reference where the AOS method is described in the context of the Anisotropic Diffusion.

**Comment by Henvezz95** [comment]
Hi @RoyiAvital,
I don't think it is possible to use AOS in conjunction with the use of the Structure Tensor.
You can check on Google Scholar if there are recent publications on the topic
